app:
  name: "Automated Quant PM"
  version: "1.0.0"
  description: "Automated Trading and Portfolio Management System"

server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 4

data:
  providers:
    - name: "yfinance"
      enabled: true
      priority: 1
      rate_limit: null
    - name: "alpha_vantage"
      enabled: true
      priority: 2
      rate_limit: 25  # requests per day

  update_intervals:
    realtime: 60  # seconds
    historical: 3600  # 1 hour

  cache:
    enabled: true
    ttl: 300  # 5 minutes

trading:
  enabled: false
  paper_trading: true

  risk_management:
    max_position_size: 0.1  # 10% of portfolio
    max_portfolio_risk: 0.2  # 20% total risk
    stop_loss_pct: 0.02  # 2% stop loss
    take_profit_pct: 0.05  # 5% take profit

  execution:
    order_type: "market"  # market, limit
    slippage: 0.001  # 0.1%
    commission: 0.001  # 0.1%

portfolio:
  rebalance_frequency: "daily"  # daily, weekly, monthly
  optimization_method: "mean_variance"  # mean_variance, risk_parity, hierarchical

models:
  default_model: "lstm"
  training:
    batch_size: 32
    epochs: 100
    learning_rate: 0.001
    validation_split: 0.2
    early_stopping_patience: 10

  pytorch:
    device: "cpu"  # cpu, cuda
    num_workers: 4
    pin_memory: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"
  rotation: "1 day"
  retention: "30 days"