# Popular Financial Instruments for Trading Dashboard
# Top 20 most popular and liquid instruments across asset classes

equities:
  us_stocks:
    - symbol: "AAPL"
      name: "Apple Inc."
      exchange: "NASDAQ"
    - symbol: "MSFT"
      name: "Microsoft Corporation"
      exchange: "NASDAQ"
    - symbol: "GOOGL"
      name: "Alphabet Inc."
      exchange: "NASDAQ"
    - symbol: "AMZN"
      name: "Amazon.com Inc."
      exchange: "NASDAQ"
    - symbol: "NVDA"
      name: "NVIDIA Corporation"
      exchange: "NASDAQ"
    - symbol: "META"
      name: "Meta Platforms Inc."
      exchange: "NASDAQ"
    - symbol: "TSLA"
      name: "Tesla Inc."
      exchange: "NASDAQ"
    - symbol: "JPM"
      name: "JPMorgan Chase & Co."
      exchange: "NYSE"
    - symbol: "V"
      name: "Visa Inc."
      exchange: "NYSE"
    - symbol: "WMT"
      name: "Walmart Inc."
      exchange: "NYSE"

etfs:
  - symbol: "SPY"
    name: "SPDR S&P 500 ETF"
    type: "US Large Cap"
  - symbol: "QQQ"
    name: "Invesco QQQ Trust"
    type: "Technology"
  - symbol: "IWM"
    name: "iShares Russell 2000 ETF"
    type: "US Small Cap"
  - symbol: "EEM"
    name: "iShares MSCI Emerging Markets ETF"
    type: "Emerging Markets"
  - symbol: "GLD"
    name: "SPDR Gold Trust"
    type: "Gold"

crypto:
  - symbol: "BTC-USD"
    name: "Bitcoin USD"
    type: "Cryptocurrency"
  - symbol: "ETH-USD"
    name: "Ethereum USD"
    type: "Cryptocurrency"

indices:
  - symbol: "^GSPC"
    name: "S&P 500"
  - symbol: "^DJI"
    name: "Dow Jones Industrial Average"
  - symbol: "^IXIC"
    name: "NASDAQ Composite"

# Default watchlist (20 instruments)
default_watchlist:
  - "AAPL"
  - "MSFT"
  - "GOOGL"
  - "AMZN"
  - "NVDA"
  - "META"
  - "TSLA"
  - "JPM"
  - "V"
  - "WMT"
  - "SPY"
  - "QQQ"
  - "IWM"
  - "EEM"
  - "GLD"
  - "BTC-USD"
  - "ETH-USD"
  - "^GSPC"
  - "^DJI"
  - "^IXIC"